# Site settings
title: Systems Thoughts
email: zhe@alienlynx.com
description: > # this means to ignore newlines until "baseurl:"
  My thoughts on life, startup and software development
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.systemsthoughts.com" # the base hostname & protocol for your site
twitter_username: linuxcity
github_username: zheli

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-google-tag-manager

# google tag manager plugin
google:
  tag_manager:
    container_id: GTM-NV9DGMR
