# Site settings
title: Systems Thoughts
email: linuxcity.jn+systemsthoughts@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My thoughts on life, startup and software development
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://systemsthoughts.com" # the base hostname & protocol for your site
twitter_username: linuxcity
github_username: zheli

# Build settings
markdown: kramdown
highlighter: rouge

# Jekyll 4.x configuration
plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# Jekyll 4.x performance settings
incremental: true
future: false
