
services:
  jekyll:
    image: bretfisher/jekyll-serve
    command: ["bundle", "exec", "jekyll", "serve", "--draft", "--livereload", "-H", "0.0.0.0", "-P", "4000" ]
    volumes:
      - .:/site
    ports:
      - '4000:4000'
